# Generated by Django 3.1.4 on 2021-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210108_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='hash_alias',
            field=models.TextField(null=True, verbose_name='Alias'),
        ),
    ]
