# Generated by Django 3.1.4 on 2021-01-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_link_hash_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hash_alias',
            field=models.TextField(blank=True, null=True, verbose_name='Alias'),
        ),
    ]
