# Generated by Django 3.1.4 on 2021-01-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210109_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Clicks'),
        ),
        migrations.AlterField(
            model_name='link',
            name='hash',
            field=models.CharField(max_length=7, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='link',
            name='hash_alias',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='link',
            name='initial_url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
