# Generated by Django 3.1.4 on 2021-01-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210111_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hash_alias',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Alias'),
        ),
    ]
