# Generated by Django 3.1.4 on 2021-01-13 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210111_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='CreatedAt'),
        ),
        migrations.AddField(
            model_name='link',
            name='ttl',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='TTL'),
        ),
    ]
