# Generated by Django 3.1.4 on 2021-01-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210113_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='ttl',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='TTL'),
        ),
    ]
